// Shared by guide and exam. No learner input leaves the browser.
export const normalizeTerm=s=>String(s).toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss');
export function matchingTerms(entries,query){const words=normalizeTerm(query).split(/\s+/).filter(Boolean);return entries.filter(e=>{const text=normalizeTerm([e.term,...(e.aliases||[]),e.de,e.en].join(' '));return words.every(w=>text.includes(w));});}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pair=(de,en)=>`<span data-no-translate><span data-reading-lang="de" lang="de">${esc(de)}</span><span data-reading-lang="en" lang="en">${esc(en)}</span></span>`;

export function mountGlossary(host,data){
 const entries=data.entries||[];if(!entries.length){host.innerHTML=`<p>${pair('Das Glossar konnte nicht geladen werden. Bitte laden Sie die Seite neu.','The glossary could not load. Please reload the page.')}</p>`;return;}let limit=30,query=new URLSearchParams(location.search).get('term')||'',practiceIndex=0;
 host.innerHTML=`<section class="fsp-glossary" data-no-translate><label>${pair('Begriff oder Bedeutung suchen','Find a term or meaning')}<input type="search" data-term-search aria-label="Begriff oder Bedeutung / Term or meaning"></label><p data-term-count role="status" aria-live="polite"></p><section class="fsp-term-practice"><h2>${pair('Ein Wort erklären','Explain one word')}</h2><p>${pair('Erklären Sie das Wort zuerst laut in einfachem Deutsch. Öffnen Sie dann das Beispiel. Es gibt keine automatische Bewertung.','First explain the word aloud in simple German. Then reveal the example. There is no automatic grading.')}</p><div data-term-drill></div><button type="button" data-term-next>${pair('Nächstes Wort','Next word')}</button></section><div data-term-results></div><button type="button" data-term-more>${pair('Weitere Wörter anzeigen','Show more words')}</button><details class="fsp-unresolved" ${(data.unresolved||[]).length?'':'hidden'}><summary>${pair('Noch unklare Quellbegriffe','Source terms still unresolved')} (${(data.unresolved||[]).length})</summary><p>${pair('Diese Einträge sind noch keine Lernkarten. Die genaue Bedeutung muss zuerst geklärt werden.','These entries are not learning cards yet. Their intended meaning needs clarification first.')}</p><ul>${(data.unresolved||[]).map(e=>`<li><strong>${esc(e.term)}</strong> — ${pair(e.reason,e.reason_en||e.reason)}</li>`).join('')}</ul></details></section>`;
 const result=host.querySelector('[data-term-results]'),drill=host.querySelector('[data-term-drill]');
 const clarification=e=>e.clarification?`<aside class="fsp-clarification"><h4>${pair('Quellbegriff geklärt','Source phrase clarified')}</h4><p>${pair(e.clarification.context.de,e.clarification.context.en)}</p><p><strong>${pair('Nicht verwechseln','Keep the distinction')}</strong>: ${pair(e.clarification.boundary.de,e.clarification.boundary.en)}</p><p>${pair('Physische PDF-Seiten','Physical PDF pages')}: ${e.clarification.pages.map(esc).join(', ')}</p></aside>`:'';
 const card=e=>`<details class="fsp-term"><summary><strong lang="de">${esc(e.term)}</strong> <span>· ${pair(e.de,e.en)}</span></summary><p>${pair(e.de,e.en)}</p>${clarification(e)}<dl><dt>${pair('Artikel','Article')}</dt><dd lang="de">${esc(e.article)||'—'}</dd><dt>${pair('Grammatik','Grammar')}</dt><dd lang="de">${esc(e.grammar_note)}${e.plural?' · Plural: '+esc(e.plural):''}</dd><dt>${pair('Einfaches Beispiel','Simple example')}</dt><dd lang="de">${esc(e.example_de)}</dd></dl>${e.aliases?.length?`<p>${pair('Schreibweisen in der Quelle','Source spellings')}: ${e.aliases.map(esc).join(' · ')}</p>`:''}${e.source_urls?.length?`<p>${pair('Nachschlagen','References')}: ${e.source_urls.map((url,i)=>/^https:\/\//.test(url)?`<a href="${esc(url)}" target="_blank" rel="noopener">${pair('Quelle','Source')} ${i+1}</a>`:'').join(' · ')}</p>`:`<p>${pair('Begriff aus dem Quellenverzeichnis; Erklärung für diesen Leitfaden verfasst.','Term from the source inventory; explanation authored for this guide.')}</p>`}</details>`;
 function renderDrill(matches){const e=matches[practiceIndex%matches.length];drill.innerHTML=e?`<h3 lang="de">${esc(e.term)}</h3><details><summary>${pair('Erklärung und Beispielsatz öffnen','Reveal explanation and example')}</summary><p lang="de">${esc(e.de)}</p><p lang="de">${esc(e.example_de)}</p><p lang="en">${esc(e.en)}</p>${clarification(e)}</details>`:`<p>${pair('Kein passendes Wort.','No matching term.')}</p>`;host.querySelector('[data-term-next]').disabled=matches.length===0;}
 function update(){const matches=matchingTerms(entries,query);result.innerHTML=matches.slice(0,limit).map(card).join('');host.querySelector('[data-term-count]').innerHTML=pair(`${matches.length} von ${entries.length} Begriffen · ${Math.min(limit,matches.length)} angezeigt`,`${matches.length} of ${entries.length} terms · ${Math.min(limit,matches.length)} shown`);host.querySelector('[data-term-more]').hidden=limit>=matches.length;renderDrill(matches);}
 host.querySelector('[data-term-search]').oninput=e=>{query=e.target.value;limit=30;practiceIndex=0;update();};
 host.querySelector('[data-term-more]').onclick=()=>{limit+=30;update();};
 host.querySelector('[data-term-next]').onclick=()=>{practiceIndex++;renderDrill(matchingTerms(entries,query));};
 host.querySelector('[data-term-search]').value=query;update();
}
